# Makefile for binfile

lib.name = binfile

class.sources = binfile.c

datafiles = binfile-help.pd

# This Makefile is based on the Makefile from pd-lib-builder written by
# Katja Vetter. You can get it from:
# https://github.com/pure-data/pd-lib-builder

include ../../../pd-lib-builder/Makefile.pdlibbuilder
