# Makefile for slip

lib.name = slip

class.sources = slipdec.c slipenc.c

datafiles = \
      slipdec-help.pd \
      slipenc-help.pd \
      slip-meta.pd \
      LICENSE.txt \
      README.txt

# This Makefile is based on the Makefile from pd-lib-builder written by
# Katja Vetter. You can get it from:
# https://github.com/pure-data/pd-lib-builder

PDLIBBUILDER_DIR=pd-lib-builder/
include $(PDLIBBUILDER_DIR)/Makefile.pdlibbuilder
