# Makefile for slip

lib.name = slip

class.sources = ../slipdec/slipdec.c ../slipenc/slipenc.c

datafiles = ../slipdec/slipdec-help.pd ../slipenc/slipenc-help.pd \
            LICENSE.txt README.txt slip-meta.pd

# This Makefile is based on the Makefile from pd-lib-builder written by
# Katja Vetter. You can get it from:
# https://github.com/pure-data/pd-lib-builder

include ../../pd-lib-builder/Makefile.pdlibbuilder
