# Makefile for midifile

lib.name = midifile

class.sources = midifile.c

datafiles = \
	midifile-help.pd #\
	midifile-meta.pd \
	README.txt \
	LICENSE.txt \
	I_Wanna_Be_Sedated.mid

# This Makefile is based on the Makefile from pd-lib-builder written by
# Katja Vetter. You can get it from:
# https://github.com/pure-data/pd-lib-builder

include ../../pd-lib-builder/Makefile.pdlibbuilder
